services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: lms-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Server=db,1433;Database=LoansDb;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=True;"
      Jwt__Issuer: "lms"
      Jwt__Audience: "lms"
      Jwt__Key: "${JWT_KEY}"
    ports:
      - "5004:8080"

volumes:
  mssql_data:
